#默认激活dev配置
spring:
  profiles:
    active: "dev"

---
spring:
  config:
    activate:
      on-profile: "dev"

name: dev.bnrmyy.com

---
spring:
  config:
    activate:
      on-profile: "test"

name: test.bnrmyy.com

---
spring:
  config:
    activate:
      on-profile: "prod"
name: prod.bnrmyy.com